//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneticPlacement.SettingFiles {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class CompareCrossOver_Mutation : global::System.Configuration.ApplicationSettingsBase {
        
        private static CompareCrossOver_Mutation defaultInstance = ((CompareCrossOver_Mutation)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CompareCrossOver_Mutation())));
        
        public static CompareCrossOver_Mutation Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string NumberOfGenerations {
            get {
                return ((string)(this["NumberOfGenerations"]));
            }
            set {
                this["NumberOfGenerations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string PopulationSize {
            get {
                return ((string)(this["PopulationSize"]));
            }
            set {
                this["PopulationSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public string UpdatePercentage {
            get {
                return ((string)(this["UpdatePercentage"]));
            }
            set {
                this["UpdatePercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string SkyLineWasteSpace {
            get {
                return ((string)(this["SkyLineWasteSpace"]));
            }
            set {
                this["SkyLineWasteSpace"] = value;
            }
        }
    }
}
